spring.application.name=multiChatClient

# Logging
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Spring AI / Ollama Configuration using Docker hosted ollama
#
#spring.ai.openai.api-key=${OPENAI_KEY}
#spring.ai.chat.client.enabled=false

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2:0.5b
## qwen2:0.5b
## gemma3:1b
#spring.ai.ollama.chat.options.format=json

spring.datasource.url=jdbc:h2:file:C:/Users/SudeepFuji/chatMemory;AUTO_SERVER=true
spring.datasource.username=sudeep
spring.datasource.password=12345
spring.datasource.driver-class-name=org.h2.Driver
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

#Docker
#spring.docker.compose.stop.command=down

# H2 Console Configuration
#
#spring.h2.console.enabled=true
#
#spring.h2.console.path=/h2-console

spring.docker.compose.file=./compose.yaml
spring.docker.compse.stop.command=down


# Expose actuator endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus
#management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Other
spring.ai.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Extra added for newer version
spring.ai.chat.observations.enabled=true
management.observations.key-values.application=rag

# OpenTelemetry Configuration
opentelemetry.exporter.otlp.endpoint=http://localhost:4317

#  default 0.1 (probability range 0.0 ~ 1.0) =  only 10% of traffic trace will be feed to the collector component.
management.tracing.sampling.probability=1.0

